image: node:8.9.0

before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
  - npm install

cache:
  paths:
    - node_modules/

stages:
  - install
  - test
  - deploy

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test

deploy:dev:
  only:
    - dev
  stage: deploy
  script:
    - bash deploy/deploy_dev.sh

deploy:master:
  only:
    - master
  stage: deploy
  script:
    - bash deploy/deploy_master.sh
